import {
  ORDER_LIFECYCLE_STATUS,
  REVENUE_RECOGNIZED_ORDER_STATUSES,
} from "./orderLifecycle";

export const REJECTED_ORDER_STATUS_VALUES = [
  ORDER_LIFECYCLE_STATUS.QUOTATION_REJECTED,
  ORDER_LIFECYCLE_STATUS.QUOTATION_EXPIRED,
  "REJECTED",
  "CANCELED",
  "CANCELLED",
  "RETURNED",
  "REFUNDED",
] as const;

export const NON_CONFIRMED_ORDER_STATUS_VALUES = [
  ORDER_LIFECYCLE_STATUS.PENDING_VERIFICATION,
  ORDER_LIFECYCLE_STATUS.WAITLISTED,
  ORDER_LIFECYCLE_STATUS.AWAITING_PAYMENT,
  ...REJECTED_ORDER_STATUS_VALUES,
] as const;

export const CONFIRMED_ORDER_STATUS_VALUES = [
  ...REVENUE_RECOGNIZED_ORDER_STATUSES,
] as const;
