export const ORDER_LIFECYCLE_STATUS = {
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  WAITLISTED: "WAITLISTED",
  AWAITING_PAYMENT: "AWAITING_PAYMENT",
  QUOTATION_REJECTED: "QUOTATION_REJECTED",
  QUOTATION_EXPIRED: "QUOTATION_EXPIRED",
  CONFIRMED: "CONFIRMED",
  DELIVERED: "DELIVERED",
} as const;

export type OrderLifecycleStatus =
  (typeof ORDER_LIFECYCLE_STATUS)[keyof typeof ORDER_LIFECYCLE_STATUS];

export const ORDER_STATUS_TRANSITIONS: Record<
  OrderLifecycleStatus,
  OrderLifecycleStatus[]
> = {
  PENDING_VERIFICATION: [
    ORDER_LIFECYCLE_STATUS.AWAITING_PAYMENT,
    ORDER_LIFECYCLE_STATUS.WAITLISTED,
  ],
  WAITLISTED: [ORDER_LIFECYCLE_STATUS.AWAITING_PAYMENT],
  AWAITING_PAYMENT: [
    ORDER_LIFECYCLE_STATUS.CONFIRMED,
    ORDER_LIFECYCLE_STATUS.QUOTATION_REJECTED,
    ORDER_LIFECYCLE_STATUS.QUOTATION_EXPIRED,
  ],
  CONFIRMED: [ORDER_LIFECYCLE_STATUS.DELIVERED],
  QUOTATION_REJECTED: [],
  QUOTATION_EXPIRED: [],
  DELIVERED: [],
};

export const REVENUE_RECOGNIZED_ORDER_STATUSES: OrderLifecycleStatus[] = [
  ORDER_LIFECYCLE_STATUS.CONFIRMED,
  ORDER_LIFECYCLE_STATUS.DELIVERED,
];

export const NON_REVENUE_ORDER_STATUSES: OrderLifecycleStatus[] = [
  ORDER_LIFECYCLE_STATUS.PENDING_VERIFICATION,
  ORDER_LIFECYCLE_STATUS.WAITLISTED,
  ORDER_LIFECYCLE_STATUS.AWAITING_PAYMENT,
  ORDER_LIFECYCLE_STATUS.QUOTATION_REJECTED,
  ORDER_LIFECYCLE_STATUS.QUOTATION_EXPIRED,
];

export const TERMINAL_ORDER_STATUSES: OrderLifecycleStatus[] = [
  ORDER_LIFECYCLE_STATUS.DELIVERED,
  ORDER_LIFECYCLE_STATUS.QUOTATION_REJECTED,
  ORDER_LIFECYCLE_STATUS.QUOTATION_EXPIRED,
];

export const DEFAULT_RESERVATION_EXPIRY_HOURS = 48;
export const DEFAULT_RESERVATION_SWEEP_SECONDS = 60;

const parsePositiveInteger = (
  value: string | undefined,
  fallback: number
): number => {
  const parsed = Number.parseInt(String(value ?? ""), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
};

export const getReservationExpiryHours = (): number =>
  parsePositiveInteger(
    process.env.ORDER_RESERVATION_EXPIRY_HOURS,
    DEFAULT_RESERVATION_EXPIRY_HOURS
  );

export const getReservationSweepSeconds = (): number =>
  parsePositiveInteger(
    process.env.ORDER_RESERVATION_SWEEP_SECONDS,
    DEFAULT_RESERVATION_SWEEP_SECONDS
  );
