export const ORDER_LIFECYCLE_STATUS = {
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  WAITLISTED: "WAITLISTED",
  AWAITING_PAYMENT: "AWAITING_PAYMENT",
  QUOTATION_REJECTED: "QUOTATION_REJECTED",
  QUOTATION_EXPIRED: "QUOTATION_EXPIRED",
  CONFIRMED: "CONFIRMED",
  DELIVERED: "DELIVERED",
} as const;

export type OrderLifecycleStatus =
  (typeof ORDER_LIFECYCLE_STATUS)[keyof typeof ORDER_LIFECYCLE_STATUS];

export const ORDER_STATUS_TRANSITIONS: Record<
  OrderLifecycleStatus,
  OrderLifecycleStatus[]
> = {
  PENDING_VERIFICATION: [
    ORDER_LIFECYCLE_STATUS.AWAITING_PAYMENT,
    ORDER_LIFECYCLE_STATUS.WAITLISTED,
  ],
  WAITLISTED: [ORDER_LIFECYCLE_STATUS.AWAITING_PAYMENT],
  AWAITING_PAYMENT: [
    ORDER_LIFECYCLE_STATUS.CONFIRMED,
    ORDER_LIFECYCLE_STATUS.QUOTATION_REJECTED,
  ],
  CONFIRMED: [ORDER_LIFECYCLE_STATUS.DELIVERED],
  QUOTATION_REJECTED: [],
  QUOTATION_EXPIRED: [],
  DELIVERED: [],
};

export const REVENUE_RECOGNIZED_ORDER_STATUSES: OrderLifecycleStatus[] = [
  ORDER_LIFECYCLE_STATUS.CONFIRMED,
  ORDER_LIFECYCLE_STATUS.DELIVERED,
];

export const NON_REVENUE_ORDER_STATUSES: OrderLifecycleStatus[] = [
  ORDER_LIFECYCLE_STATUS.PENDING_VERIFICATION,
  ORDER_LIFECYCLE_STATUS.WAITLISTED,
  ORDER_LIFECYCLE_STATUS.AWAITING_PAYMENT,
  ORDER_LIFECYCLE_STATUS.QUOTATION_REJECTED,
  ORDER_LIFECYCLE_STATUS.QUOTATION_EXPIRED,
];

export const TERMINAL_ORDER_STATUSES: OrderLifecycleStatus[] = [
  ORDER_LIFECYCLE_STATUS.DELIVERED,
  ORDER_LIFECYCLE_STATUS.QUOTATION_REJECTED,
  ORDER_LIFECYCLE_STATUS.QUOTATION_EXPIRED,
];
