-- Replace old transaction status enum with no-payment order lifecycle values.
ALTER TYPE "TRANSACTION_STATUS" RENAME TO "TRANSACTION_STATUS_OLD";

CREATE TYPE "TRANSACTION_STATUS" AS ENUM (
  'PLACED',
  'CONFIRMED',
  'REJECTED',
  'DELIVERED'
);

ALTER TABLE "Transaction"
ALTER COLUMN "status" DROP DEFAULT;

ALTER TABLE "Transaction"
ALTER COLUMN "status" TYPE "TRANSACTION_STATUS"
USING (
  CASE
    WHEN "status"::text = 'PENDING' THEN 'PLACED'
    WHEN "status"::text IN ('PROCESSING', 'SHIPPED', 'IN_TRANSIT') THEN 'CONFIRMED'
    WHEN "status"::text = 'DELIVERED' THEN 'DELIVERED'
    WHEN "status"::text IN ('CANCELED', 'RETURNED', 'REFUNDED') THEN 'REJECTED'
    ELSE 'PLACED'
  END
)::"TRANSACTION_STATUS";

ALTER TABLE "Transaction"
ALTER COLUMN "status" SET DEFAULT 'PLACED';

DROP TYPE "TRANSACTION_STATUS_OLD";

-- Keep order.status string for compatibility, but normalize existing values.
UPDATE "Order"
SET "status" = CASE
  WHEN UPPER("status") = 'PLACED' THEN 'PLACED'
  WHEN UPPER("status") = 'PENDING' THEN 'PLACED'
  WHEN UPPER("status") IN ('CONFIRMED', 'PROCESSING', 'SHIPPED', 'IN_TRANSIT') THEN 'CONFIRMED'
  WHEN UPPER("status") = 'DELIVERED' THEN 'DELIVERED'
  WHEN UPPER("status") IN ('REJECTED', 'CANCELED', 'RETURNED', 'REFUNDED') THEN 'REJECTED'
  ELSE 'PLACED'
END;

ALTER TABLE "Order"
ALTER COLUMN "status" SET DEFAULT 'PLACED';
