version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_API_URL_DEV=http://localhost:5000/api/v1
      - NEXT_PUBLIC_API_URL_PROD=http://localhost:5000/api/v1
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://jhaecom:jhaecom27@db:5432/b2c_ecommerce
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev -- --legacy-watch

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: jhaecom
      POSTGRES_PASSWORD: jhaecom27
      POSTGRES_DB: b2c_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
